Refactor AnyNet to replace keras.Model subclass with fn API (#4)
* wip refactor to functional anynet model

* working anynet_fn arch

* rm anynet module using keras.Model subclass

* rm unused kwargs to Anynet

* add get_config serializers to custom layers, update DepthMapImageCallback to work with functional flow

* clean up misleading comments

* File "/home/leigh/projects/tf-anynet/tf_anynet/models/dispnet.py", line 174, in call
    cost = self._build_volume_2d(feats_l[scale], feats_r[scale],
  File "/home/leigh/projects/tf-anynet/tf_anynet/models/dispnet.py", line 65, in _build_volume_2d
    cost = tf.Variable(
  File "/home/leigh/projects/tf-anynet/.venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 261, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/home/leigh/projects/tf-anynet/.venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 243, in _variable_v2_call
    return previous_getter(
  File "/home/leigh/projects/tf-anynet/.venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 66, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/home/leigh/projects/tf-anynet/.venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2562, in creator
    return next_creator(**kwargs)
  File "/home/leigh/projects/tf-anynet/.venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 66, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/home/leigh/projects/tf-anynet/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 510, in invalid_creator_scope
    raise ValueError(
ValueError: tf.function-decorated function tried to create variables on non-first call.

* increase sample num, change callback to on_epoch_end

* fix get_config defs

* add ds.shuffle